
# Rules
# Docs: https://realm.github.io/SwiftLint/rule-directory.html

included:
    - ../App
    - ../UITests
    - ../TicketPartyPackage/Package.swift
    - ../TicketPartyPackage/Sources
    - ../TicketPartyPackage/TicketPartyTests

excluded:
    - ../.build
    - ../.swiftpm
    - ../TicketPartyPackage/.build
    - ../TicketPartyPackage/.swiftpm

opt_in_rules:
    - array_init
    - closure_spacing
    - comma_inheritance
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - discouraged_assert
    - discouraged_none_name
    - empty_collection_literal
    - empty_count
    - empty_string
    - enum_case_associated_values_count
    - fallthrough
    - fatal_error_message
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - last_where
    - legacy_multiple
    - legacy_objc_type
    - modifier_order
    - overridden_super_call
    - prefer_self_in_static_references
    - private_action
    - private_outlet
    - strict_fileprivate
    - toggle_bool

disabled_rules:
    - trailing_whitespace # Handled by SwiftFormat
    - line_length
    - function_body_length
    - closure_body_length
    - type_body_length
    - file_length
    - type_name
    - multiple_closures_with_trailing_closure
    - opening_brace
    - implicit_optional_initialization
    - trailing_comma # Handled by SwiftFormat
    - vertical_whitespace # Handled by SwiftFormat
    - todo

# Rule Parameters

cyclomatic_complexity:
    warning: 20
    error: 50

duplicate_conditions:
    severity: warning # TODO: make error

enum_case_associated_values_count:
    warning: 10
    error: 20

empty_count:
    severity: error
    only_after_dot: true

fatal_error_message:
    severity: error

force_try:
    severity: error

force_cast:
    severity: warning

function_parameter_count:
    warning: 8
    error: 10

identifier_name:
    min_length:
        warning: 2
        error: 1
    max_length:
        warning: 60
    validates_start_with_lowercase: warning

large_tuple:
    warning: 2
    error: 4

nesting:
    type_level:
        warning: 3
        error: 5
    function_level:
        warning: 2
        error: 3

overridden_super_call:
    severity: error

shorthand_operator:
    severity: error
